services:
  postgres:
    image: 'postgres:12-alpine'
    environment:
      - 'POSTGRES_DB=token-database'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5431:5432'

